/**
 * The list of vendored runtime files, read from `public/` at build time.
 *
 * `public/vendor/` is generated by the `prebuild` scripts and git-ignored, so nothing may assume a
 * fixed set of names or that the directory exists at all: `pnpm dev` on a fresh checkout has none
 * of it. The playground renders whatever is there into a JSON script tag, which is what the
 * service worker downloads when a reader asks for offline runtimes.
 *
 * Node-only, by design — it is imported from `.astro` frontmatter, never from an island.
 */
import { existsSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';

export interface VendorFile {
  /** Site-absolute URL, e.g. `/vendor/pyodide/pyodide.asm.wasm`. */
  url: string;
  bytes: number;
}

/** Every file under `public/vendor/`, sorted, or an empty list when it has not been vendored. */
export function vendorFiles(root = path.join(process.cwd(), 'public/vendor')): VendorFile[] {
  if (!existsSync(root)) return [];

  const found: VendorFile[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile()) {
        found.push({
          url: `/vendor/${path.relative(root, full).split(path.sep).join('/')}`,
          bytes: statSync(full).size,
        });
      }
    }
  };
  walk(root);
  return found.sort((a, b) => a.url.localeCompare(b.url));
}

/** Rounded megabytes, for the "≈30 MB" the download button has to be honest about. */
export function vendorMegabytes(files: VendorFile[]): number {
  return Math.round(files.reduce((total, file) => total + file.bytes, 0) / 1024 / 1024);
}
